---
- name: Initial server setup
  hosts: all
  gather_facts: true
  remote_user: "{{ remote_user | default('ubuntu', true) }}"
  become: yes
  roles:
    # - role: setup-common
    #   vars:
    #     create_user: vc
    #     packages:
    #       ["curl", "vim", "git", "unzip", "make", "gcc", "jq", "htop", "acl"]
    # - role: node-exporter
    #   vars:
    #     node_exporter_version: 1.2.2
    - role: chrony
