---
- name: Gather variables for each processor architecture
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_architecture | lower }}.yml"

- name: Install lighthouse binary from remote source
  block:
    - name: create new directory for binary
      file:
        path: "{{ base_path }}/lighthouse/{{ release_tag }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
    - name: Unarchive lighthouse Release file from github
      unarchive:
        src: "https://github.com/sigp/lighthouse/releases/download/v{{ release_tag }}/lighthouse-v{{ release_tag }}-{{ arch }}-unknown-linux-gnu-portable.tar.gz"
        dest: "{{ base_path }}/lighthouse/{{ release_tag }}"
        remote_src: yes
        creates: "{{ base_path }}/lighthouse/{{ release_tag }}/lighthouse"
    - name: copy binary to PATH bin
      copy:
        src: "{{ base_path }}/lighthouse/{{ release_tag }}/lighthouse"
        dest: "{{ base_path }}/bin/lighthouse"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "755"
        remote_src: yes
        force: yes

- name: create data directory
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Create lighthouse-beacon service file
  template:
    src: lighthouse-beacon.service.j2
    dest: /etc/systemd/system/lighthouse-beacon.service
    mode: "644"

- name: systemd daemon-reload
  become: yes
  systemd:
    daemon_reload: yes

- name: Enable service lighthouse-beacon and ensure it is not masked
  systemd:
    name: lighthouse-beacon
    enabled: yes
    masked: no

- name: Start lighthouse-beacon
  systemd:
    state: restarted
    daemon_reload: yes
    name: lighthouse-beacon
